server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          __path__: /tmp/app-logs/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: msg
            timestamp: time
            trace_id: trace_id
            span_id: span_id
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          trace_id:
          span_id:
