global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    scheme: http
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "tempo"
    scheme: http
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "node_exporter"
    scheme: http
    static_configs:
      - targets: ["node_exporter:9100"]
    scrape_interval: 15s
