name: Pull Request Checks 🔍
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ⤵️
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Setup DB
        run: make up

      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: "1.29.0"

      - run: sqlc diff

      - name: Install goose
        run: |
          curl -fsSL \
            https://raw.githubusercontent.com/pressly/goose/master/install.sh |\
            sh

      - name: Run Migrations
        run: make migrate-test

      - name: Run tests
        run: make test
